### ISSUE TITLE
Problemas no carregamento da imagem.

### ISSUE THREAD

**Issue by FabianoPrazeres** [nglauber/dominando_android2#2]
Boa tarde a todos!
Estou estudando este livro maravilhoso do Prof Nelson Glauber, e  ao terminar o estudo da página 355 da 2º Edição, o meu exemplo não carregou as devidas imagens.
Toda a parte restante como as informações de Titulo, autor, ano e numero de páginas carregou corretamente, porém a imagem que faz parte do exemplo fica em "branco".
Já revisei meu código algumas vezes, porém não consegui visualizar o motivo do não carregamento.
Se alguém souber me dizer a possível solução do problema, ou os principais códigos os quais devo revisar para tentar encontrar o problema.
Bons estudos a todos, e PARABÉNS ao professor pelo excelente material didático.
Att; Fabiano S Prazeres

**Comment by nglauber** [comment]
Obrigado @FabianoPrazeres! Que bom que está gostando do livro :)
O problema é que a novatec mudou o endereço das imagens, então o endereço das capas que está vindo no JSON está errado. Acabei de corrigir. Tenta novamente e vê se está ok ;) E obrigado por reportar o problema.

**Comment by FabianoPrazeres** [comment]
Problema resolvido, carregou corretamente agora.
Professor @nglauber , muito obrigado pela rapidez e agilidade em sua resposta, fiquei dois dias tentando achar o erro e "debugando" e não conseguia, mais uma vez receba meus parabéns pelo seu trabalho, estudo Android através de mais dois materiais didáticos, e sem sombra de dúvidas o seu Material é o melhor e mais explicativo. Obrigada!!!
